GET http://localhost:5000/catatan

###
GET http://localhost:5000/users/1

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "putri@gmail",
    "password": "12345"
}

###
PATCH http://localhost:5000/users/1
Content-Type: application/json

{
    "judul": "KEBUTUHAN BULAN JANUARI",
    "catatan": "BAYAR UKT, BAYAR KOS",
    "kategori": "PRIBADI"
}

###
DELETE http://localhost:5000/users/2